# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
networks:
  default: polygon_main_infura
  mainnet-fork:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  kovan:
    aave_lending_pool_v2: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    weth: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
  mainnet:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  Polygon: 
    aave_lending_pool_v3: "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
    aDAI: "0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE"      
  polygon_main_infura: 
    aave_lending_pool_v3: "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
    #USDT: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
    aDAI: "0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE"      
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
  
dotenv: .env

settings:
  gas_limit: "100000000000000"

